// <auto-generated />
using System;
using DwhiePaint.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DwhiePaint.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703140558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DwhiePaint.Api.Domain.ColorDictionaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hex");

                    b.Property<float>("LabA")
                        .HasColumnType("real")
                        .HasColumnName("lab_a");

                    b.Property<float>("LabB")
                        .HasColumnType("real")
                        .HasColumnName("lab_b");

                    b.Property<float>("LabL")
                        .HasColumnType("real")
                        .HasColumnName("lab_l");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ru");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_color_dictionary");

                    b.ToTable("color_dictionary", (string)null);
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_images_user_id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Painting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ColorCount")
                        .HasColumnType("integer")
                        .HasColumnName("color_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("ResultPath")
                        .HasColumnType("text")
                        .HasColumnName("result_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_paintings");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("ix_paintings_image_id");

                    b.ToTable("paintings", (string)null);
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.PaletteColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("integer")
                        .HasColumnName("color_index");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hex");

                    b.Property<float>("LabA")
                        .HasColumnType("real")
                        .HasColumnName("lab_a");

                    b.Property<float>("LabB")
                        .HasColumnType("real")
                        .HasColumnName("lab_b");

                    b.Property<float>("LabL")
                        .HasColumnType("real")
                        .HasColumnName("lab_l");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ru");

                    b.Property<Guid>("PaintingId")
                        .HasColumnType("uuid")
                        .HasColumnName("painting_id");

                    b.HasKey("Id")
                        .HasName("pk_palette_colors");

                    b.HasIndex("PaintingId")
                        .HasDatabaseName("ix_palette_colors_painting_id");

                    b.ToTable("palette_colors", (string)null);
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Image", b =>
                {
                    b.HasOne("DwhiePaint.Api.Domain.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_images_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Painting", b =>
                {
                    b.HasOne("DwhiePaint.Api.Domain.Image", "Image")
                        .WithMany("Paintings")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paintings_images_image_id");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.PaletteColor", b =>
                {
                    b.HasOne("DwhiePaint.Api.Domain.Painting", "Painting")
                        .WithMany("PaletteColors")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_palette_colors_paintings_painting_id");

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Image", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.Painting", b =>
                {
                    b.Navigation("PaletteColors");
                });

            modelBuilder.Entity("DwhiePaint.Api.Domain.User", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
